// <auto-generated />
namespace DoanWeb_BanGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202107110332391_EditStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
